spring.application.name=api-gateway
server.port=9000

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

#----------------------------
# Tells Spring where to fetch Keycloak's JWKS (public keys) to verify JWT signatures. 
# Spring auto-discovers the /.well-known/openid-configuration endpoint from this URI.

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/springboot-microservices-ecommerce-security-realm

# The jwk-set-uri is more explicit and avoids the extra discovery HTTP call on startup. Either works fine.

#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8181/realms/springboot-microservices-ecommerce-security-realm/protocol/openid-connect/certs

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.urls[0].name=product-service
springdoc.swagger-ui.urls[0].url=/aggregate/product-service/v3/api-docs
springdoc.swagger-ui.urls[1].name=order-service
springdoc.swagger-ui.urls[1].url=/aggregate/order-service/v3/api-docs
springdoc.swagger-ui.urls[2].name=inventory-service
springdoc.swagger-ui.urls[2].url=/aggregate/inventory-service/v3/api-docs
