spring.application.name=product-service
spring.mongodb.uri=mongodb://root:password@localhost:27017/product-service?authSource=admin
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Loki Logging
app.loki.url=http://localhost:3100/loki/api/v1/push

# Actuator & Prometheus Metrics
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.prometheus.access=unrestricted
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.observations.key-values.application=${spring.application.name}

# Tracing (Tempo/OTLP)
management.tracing.sampling.probability=1.0
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces
